# Generated by Django 5.2.3 on 2025-06-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('lang', models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], max_length=2, null=True)),
            ],
        ),
    ]
